version: "3"
services:
  canary-redis:
    image: "redis:alpine"

    container_name: canary-redis

    command: redis-server --port ${REDIS_PORT} --requirepass ${REDIS_PASSWORD} --appendonly yes

    expose:
      - ${REDIS_PORT}
    restart: always

  canary-db:
    image: mysql:8.0
    hostname: "canary-db"
    container_name: canary-db

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_TCP_PORT: ${DB_PORT}
    volumes:
      - ${HOME}/.canary/data/mysql:/var/lib/mysql:rw
      - ../server/deploy/voice.sql:/docker-entrypoint-initdb.d/voice.sql:ro
    expose:
      - ${DB_PORT}
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  canary-minio:
    image: "minio/minio"
    hostname: "canary-minio"
    container_name: canary-minio

    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - ${HOME}/.canary/data/minio:/data
    command: server --address ":${MINIO_PORT}" --console-address ":${MINIO_CONSOLE_PORT}" /data
    privileged: true
    restart: always

  rq-dashboard:
    image: eoranged/rq-dashboard
    hostname: "canary-rq-dashboard"
    container_name: canary-rq-dashboard

    command: -u redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/0
    environment:
      RQ_DASHBOARD_USERNAME: ${RQ_DASHBOARD_USERNAME}
      RQ_DASHBOARD_PASSWORD: ${RQ_DASHBOARD_PASSWORD}
    ports:
      - 39181:9181
    depends_on:
      - canary-redis

  canary-web:
    container_name: canary-web

    build:
      context: "../web"
      dockerfile: "./Dockerfile"
    volumes:
      - dist:/usr/src/app/dist
    depends_on:
      - canary-server
    ports:
      - 10005:80

  canary-server:
    container_name: canary-server
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      EMAIL_SMTP_SERVER: ${EMAIL_SMTP_SERVER}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_SSL: ${EMAIL_SSL}

      JWT_SALT: ${JWT_SALT}

      MINIO_HOST: ${MINIO_HOST}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}

      PODCAST_SHARE_SECRET_SALT: ${PODCAST_SHARE_SECRET_SALT}

    build:
      context: ../server
      dockerfile: ./Dockerfile
      target: server
    depends_on:
      - canary-db
      - canary-redis
      - canary-minio
    volumes:
      - ${HOME}/.ttsvm:/root/.ttsvm
    ports:
      - 8576:8576
    restart: always

  canary-scheduler:
    container_name: canary-scheduler
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      EMAIL_SMTP_SERVER: ${EMAIL_SMTP_SERVER}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_SSL: ${EMAIL_SSL}

      JWT_SALT: ${JWT_SALT}

      MINIO_HOST: ${MINIO_HOST}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}

      PODCAST_SHARE_SECRET_SALT: ${PODCAST_SHARE_SECRET_SALT}

    build:
      context: ../server
      dockerfile: ./Dockerfile
      target: scheduler
    depends_on:
      - canary-db
      - canary-redis
      - canary-minio
    volumes:
      - ${HOME}/.ttsvm:/root/.ttsvm
    ports:
      - 8576:8576
    restart: always

  canary-other:
    container_name: canary-other

    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      EMAIL_SMTP_SERVER: ${EMAIL_SMTP_SERVER}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_SSL: ${EMAIL_SSL}

      JWT_SALT: ${JWT_SALT}

      MINIO_HOST: ${MINIO_HOST}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}

      PODCAST_SHARE_SECRET_SALT: ${PODCAST_SHARE_SECRET_SALT}
    build:
      context: ../server
      dockerfile: ./Dockerfile
      target: job
      args:
        JOB: other
    depends_on:
      - canary-db
      - canary-redis
      - canary-minio
    volumes:
      - ${HOME}/.ttsvm:/root/.ttsvm
    restart: always

  canary-en1:
    container_name: canary-en1

    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      EMAIL_SMTP_SERVER: ${EMAIL_SMTP_SERVER}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_SSL: ${EMAIL_SSL}

      JWT_SALT: ${JWT_SALT}

      MINIO_HOST: ${MINIO_HOST}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}

      PODCAST_SHARE_SECRET_SALT: ${PODCAST_SHARE_SECRET_SALT}
    build:
      context: ../server
      dockerfile: ./Dockerfile
      target: job
      args:
        JOB: en
    depends_on:
      - canary-db
      - canary-redis
      - canary-minio
    volumes:
      - ${HOME}/.ttsvm:/root/.ttsvm
    restart: always

  canary-zh1:
    container_name: canary-zh1

    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      EMAIL_SMTP_SERVER: ${EMAIL_SMTP_SERVER}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_SSL: ${EMAIL_SSL}

      JWT_SALT: ${JWT_SALT}

      MINIO_HOST: ${MINIO_HOST}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}

      PODCAST_SHARE_SECRET_SALT: ${PODCAST_SHARE_SECRET_SALT}
    build:
      context: ../server
      dockerfile: ./Dockerfile
      target: job
      args:
        JOB: zh
    depends_on:
      - canary-db
      - canary-redis
      - canary-minio
    volumes:
      - ${HOME}/.ttsvm:/root/.ttsvm
    restart: always

  canary-zh2:
    container_name: canary-zh2

    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      EMAIL_SMTP_SERVER: ${EMAIL_SMTP_SERVER}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_SSL: ${EMAIL_SSL}

      JWT_SALT: ${JWT_SALT}

      MINIO_HOST: ${MINIO_HOST}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}

      PODCAST_SHARE_SECRET_SALT: ${PODCAST_SHARE_SECRET_SALT}
    build:
      context: ../server
      dockerfile: ./Dockerfile
      target: job
      args:
        JOB: zh
    depends_on:
      - canary-db
      - canary-redis
      - canary-minio
    volumes:
      - ${HOME}/.ttsvm:/root/.ttsvm
    restart: always

  canary-zh3:
    container_name: canary-zh3

    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      EMAIL_SMTP_SERVER: ${EMAIL_SMTP_SERVER}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_SSL: ${EMAIL_SSL}

      JWT_SALT: ${JWT_SALT}

      MINIO_HOST: ${MINIO_HOST}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}

      PODCAST_SHARE_SECRET_SALT: ${PODCAST_SHARE_SECRET_SALT}
    build:
      context: ../server
      dockerfile: ./Dockerfile
      target: job
      args:
        JOB: zh
    depends_on:
      - canary-db
      - canary-redis
      - canary-minio
    volumes:
      - ${HOME}/.ttsvm:/root/.ttsvm
    restart: always

volumes:
  dist:
