FROM python:3.9.13-buster as base
SHELL ["/bin/bash", "-c"]
WORKDIR /usr/src/app
COPY . ./
RUN chmod +x ./entrypoint.sh
RUN python -m venv ./venv \
    && source venv/bin/activate \
    && pip install  -r requirements.txt --no-dependencies \
    && pip install paddlepaddle==2.2.2 -i https://mirror.baidu.com/pypi/simple


FROM base as server
WORKDIR /usr/src/app


FROM base as job
ARG JOB
ENV JOB ${JOB}
SHELL ["/bin/bash", "-c"]
WORKDIR /usr/src/app
RUN set -x; apt update -y \
    && apt install ffmpeg calibre -y \
    && apt remove calibre -y \
    && wget https://download.calibre-ebook.com/5.42.0/calibre-5.42.0-x86_64.txz -O /tmp/calibre-5.42.0-x86_64.txz \
    && mkdir -p /opt/calibre && rm -rf /opt/calibre/* && tar xvf /tmp/calibre-5.42.0-x86_64.txz -C /opt/calibre && /opt/calibre/calibre_postinstall \
    && source venv/bin/activate \
    && python -m playwright install \
    && apt clean && apt-get autoclean && rm /tmp/calibre-5.42.0-x86_64.txz

ENTRYPOINT ./entrypoint.sh rq --name=${JOB}



FROM base as scheduler
WORKDIR /usr/src/app
ENTRYPOINT ./entrypoint.sh scheduler


